// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmesIsel.Api.Data;

#nullable disable

namespace UmesIsel.Api.Migrations
{
    [DbContext(typeof(IselDbContext))]
    [Migration("20260826101612_PensumCatalogAndFichaCleanup")]
    partial class PensumCatalogAndFichaCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AdditionalCourseRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CursoAdicional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jornada")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemTri")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseAssignmentId");

                    b.ToTable("AdditionalCourseRows");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AssignedCourseRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemTri")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseAssignmentId");

                    b.ToTable("AssignedCourseRows");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorizadoPorCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TienePendientesMaterias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TienePendientesTrimestres")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseAssignments");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Carnet")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AdditionalCourseRow", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.CourseAssignment", "CourseAssignment")
                        .WithMany("CursosAdicionales")
                        .HasForeignKey("CourseAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssignment");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AssignedCourseRow", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.CourseAssignment", "CourseAssignment")
                        .WithMany("CursosAsignados")
                        .HasForeignKey("CourseAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssignment");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CourseAssignment", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Student", "Student")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CourseAssignment", b =>
                {
                    b.Navigation("CursosAdicionales");

                    b.Navigation("CursosAsignados");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Student", b =>
                {
                    b.Navigation("CourseAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
