// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmesIsel.Api.Data;

#nullable disable

namespace UmesIsel.Api.Migrations
{
    [DbContext(typeof(IselDbContext))]
    [Migration("20260902151128_AddSeguridadCuentasYBitacora")]
    partial class AddSeguridadCuentasYBitacora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AdditionalCourseRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CursoAdicional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jornada")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemTri")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseAssignmentId");

                    b.ToTable("AdditionalCourseRows");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BloqueadaHasta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dpi")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsExtranjero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MigradoEn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MigradoStudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pasaporte")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerNombre")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Dpi");

                    b.HasIndex("MigradoStudentId");

                    b.HasIndex("Pasaporte");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.ApplicantDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId", "Tipo")
                        .IsUnique();

                    b.ToTable("ApplicantDocuments");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TienePendientesMaterias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TienePendientesTrimestres")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique();

                    b.ToTable("AsignacionesNuevoIngreso");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngresoAdicionalRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignacionNuevoIngresoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CursoAdicional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jornada")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemTri")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionNuevoIngresoId");

                    b.ToTable("AsignacionNuevoIngresoAdicionalRows");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngresoCursoRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignacionNuevoIngresoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemTri")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionNuevoIngresoId");

                    b.ToTable("AsignacionNuevoIngresoCursoRows");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AssignedCourseRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SemTri")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseAssignmentId");

                    b.ToTable("AssignedCourseRows");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPrograma")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CartaCompromiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsExtranjero")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoDpi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique();

                    b.ToTable("CartasCompromiso");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Carrera", "Trimestre", "Nombre")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutorizadoPorCodigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TienePendientesMaterias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TienePendientesTrimestres")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoPago")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseAssignments");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Preinscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlergiaDescripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComunidadLinguistica")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionCompleta")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dpi")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emergencia1Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emergencia1Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emergencia2Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Emergencia2Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdiomaMaterno")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Jornada")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("LugarNacimiento")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoPasaporte")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("PuebloPertenencia")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SaludDescripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoCasa")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoCelular")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TieneAlergia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TieneProblemaSalud")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique();

                    b.ToTable("Preinscripciones");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.SecurityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAlerta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OcurridoEn");

                    b.HasIndex("EsAlerta", "OcurridoEn");

                    b.ToTable("SecurityEvents");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.SolicitudTitulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Campus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionDomicilio")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionTrabajo")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Empresa")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Entregada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EntregadaEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultadDepartamento")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirmadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParticipaCeremonia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefonoCelular")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoDomicilio")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoTrabajo")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloObtener")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Carnet");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("SolicitudesTitulo");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PapeleriaEnOrden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Seccion")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Trimestre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Carnet")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.StudentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Tipo")
                        .IsUnique();

                    b.ToTable("StudentDocuments");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AdditionalCourseRow", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.CourseAssignment", "CourseAssignment")
                        .WithMany("CursosAdicionales")
                        .HasForeignKey("CourseAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssignment");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Applicant", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Student", "MigradoStudent")
                        .WithMany()
                        .HasForeignKey("MigradoStudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MigradoStudent");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.ApplicantDocument", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Applicant", "Applicant")
                        .WithMany("Documentos")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngreso", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Applicant", "Applicant")
                        .WithOne("AsignacionNuevoIngreso")
                        .HasForeignKey("UmesIsel.Api.Models.Entities.AsignacionNuevoIngreso", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngresoAdicionalRow", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.AsignacionNuevoIngreso", "AsignacionNuevoIngreso")
                        .WithMany("CursosAdicionales")
                        .HasForeignKey("AsignacionNuevoIngresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionNuevoIngreso");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngresoCursoRow", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.AsignacionNuevoIngreso", "AsignacionNuevoIngreso")
                        .WithMany("CursosAsignados")
                        .HasForeignKey("AsignacionNuevoIngresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionNuevoIngreso");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AssignedCourseRow", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.CourseAssignment", "CourseAssignment")
                        .WithMany("CursosAsignados")
                        .HasForeignKey("CourseAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseAssignment");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CartaCompromiso", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Applicant", "Applicant")
                        .WithOne("CartaCompromiso")
                        .HasForeignKey("UmesIsel.Api.Models.Entities.CartaCompromiso", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CourseAssignment", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Student", "Student")
                        .WithMany("CourseAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Preinscripcion", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Applicant", "Applicant")
                        .WithOne("Preinscripcion")
                        .HasForeignKey("UmesIsel.Api.Models.Entities.Preinscripcion", "ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.SolicitudTitulo", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.StudentDocument", b =>
                {
                    b.HasOne("UmesIsel.Api.Models.Entities.Student", "Student")
                        .WithMany("Documentos")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Applicant", b =>
                {
                    b.Navigation("AsignacionNuevoIngreso");

                    b.Navigation("CartaCompromiso");

                    b.Navigation("Documentos");

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.AsignacionNuevoIngreso", b =>
                {
                    b.Navigation("CursosAdicionales");

                    b.Navigation("CursosAsignados");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.CourseAssignment", b =>
                {
                    b.Navigation("CursosAdicionales");

                    b.Navigation("CursosAsignados");
                });

            modelBuilder.Entity("UmesIsel.Api.Models.Entities.Student", b =>
                {
                    b.Navigation("CourseAssignments");

                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
